### ISSUE TITLE
Can you please share your training configuration?

### ISSUE THREAD

**Issue by mlinmg** [chenhaoxing/HDNet#12]
I have tried muliple times to train your model but I constantly hit stall around this values MSE:20.184, PSNR:39.458, fMSE:217.668, SSIM:0.992 which, while still being quite good, are not the one described in the paper.
I would like to see the configuration you used to train it. This is mine:
```
----------------- Options ---------------
               batch_size: 90                            	[default: 12]
                    beta1: 0.9                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                crop_size: 512                           	[default: 256]
               d_lr_ratio: 1.0                           
             dataset_mode: iharmony4                     
             dataset_root: ./data/harmony	[default: ./datasets/IH256/]
              display_env: main                          
             display_freq: 500                           
               display_id: 1                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: latest                        
              epoch_count: 1                             
               g_lr_ratio: 1.0                           
                 gan_mode: vanilla                       
                 gp_ratio: 1.0                           
                  gpu_ids: 0,1                           	[default: 0]
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: True                          	[default: None]
                 is_train: True                          
                lambda_L1: 1.0                           
                 lambda_a: 1.0                           
                 lambda_v: 1.0                           
                load_iter: 0                             
                load_size: 256                           
                       lr: 0.001                         
           lr_decay_iters: 100                           
                lr_policy: target_decay                  
         max_dataset_size: inf                           
                    model: hdnet                         
               n_layers_D: 3                             
                     name: armonizzatoremm               	[default: experiment_train]
                      ndf: 64                            
                     netD: basic                         
                     netG: hdnet                         
                      ngf: 32                            
                    niter: 120                           
              niter_decay: 0                             
               no_dropout: False                         
                  no_html: False                         
                    normD: instance                      
                    normG: RAIN                          
              num_threads: 15                            	[default: 32]
                output_nc: 3                             
                    phase: train                         
                pool_size: 0                             
               preprocess: none                          
               print_freq: 300                           
             save_by_iter: False                         
          save_epoch_freq: 1                             
         save_latest_freq: 5000                          
           serial_batches: False                         
                   suffix:                               
         update_html_freq: 500                           
                  verbose: False                         
----------------- End -------------------
```
